-- Create example user: Aid@gmail.com with password: 123
-- Note: Password hash is for password "123" using bcrypt with 10 rounds
-- You can run this directly in PostgreSQL or psql

-- First, check if user exists
SELECT id, email, name, role FROM users WHERE email = 'Aid@gmail.com';

-- If user doesn't exist, insert them
-- Password hash for "123" (bcrypt, 10 rounds)
INSERT INTO users (email, password_hash, name, role)
VALUES (
  'Aid@gmail.com',
  '$2a$10$rOzJqJqJqJqJqJqJqJqJqOqJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq',  -- This is a placeholder, will be generated by bcrypt
  'AID User',
  'customer'
)
ON CONFLICT (email) DO NOTHING;

-- Note: The password hash above is a placeholder.
-- In production, use the Node.js script to generate the correct hash.







